import java.awt.Color;
import java.util.Random;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class singleplayer extends javax.swing.JFrame {

    /**
     * Creates new form singleplayer
     */
    public singleplayer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        Rest = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1009, 800));

        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 213));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("You");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setText("computer");

        l1.setFont(new java.awt.Font("Tahoma", 0, 100)); // NOI18N
        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l2.setFont(new java.awt.Font("Tahoma", 0, 100)); // NOI18N
        l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Back.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        Back.setText("Back");
        Back.setMaximumSize(new java.awt.Dimension(145, 67));
        Back.setMinimumSize(new java.awt.Dimension(145, 67));
        Back.setPreferredSize(new java.awt.Dimension(145, 67));
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Rest.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        Rest.setText("Rest");
        Rest.setMaximumSize(new java.awt.Dimension(127, 67));
        Rest.setMinimumSize(new java.awt.Dimension(127, 67));
        Rest.setPreferredSize(new java.awt.Dimension(127, 67));
        Rest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(150, 150, 150)
                .addComponent(Rest, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Rest, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(Back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setLayout(new java.awt.GridLayout(3, 3, 5, 5));

        b7.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        jPanel3.add(b7);

        b8.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        jPanel3.add(b8);

        b9.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        jPanel3.add(b9);

        b4.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel3.add(b4);

        b5.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        jPanel3.add(b5);

        b6.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        jPanel3.add(b6);

        b1.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel3.add(b1);

        b2.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel3.add(b2);

        b3.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel3.add(b3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1009, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestActionPerformed
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
        b1.setBackground(Color.lightGray);
        b2.setBackground(Color.lightGray);
        b3.setBackground(Color.lightGray);
        b4.setBackground(Color.lightGray);
        b5.setBackground(Color.lightGray);
        b6.setBackground(Color.lightGray);
        b7.setBackground(Color.lightGray);
        b8.setBackground(Color.lightGray);
        b9.setBackground(Color.lightGray);
    }//GEN-LAST:event_RestActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        b1.setText("X");
        computer();
        win();
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        b2.setText("X");
        computer();
        win();
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        b3.setText("X");
        computer();
        win();
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        b4.setText("X");
        computer();
        win();
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        b5.setText("X");
        computer();
        win();
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        b6.setText("X");
        computer();
        win();
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        b7.setText("X");
        computer();
        win();
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        b8.setText("X");
        computer();
        win();
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        b9.setText("X");
        computer();
        win();
    }//GEN-LAST:event_b9ActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        main main=new main();
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    int xcount=0;
    int ocount=0;
    public void computer()
    {
        Random x=new Random();
        int y=x.nextInt(9);
        if(y==0)
        {
        y=x.nextInt(9);
        }
    switch(y)
    {
        case 1:{if(b1.getText()=="")
                   b1.setText("O");
        else 
        {computer();}}
        break;
        case 2:{if(b2.getText()=="")
                b2.setText("O");
        else 
        {computer();}}
        break;
        case 3:{if(b3.getText()=="")
                b3.setText("O");
        else 
        {computer();}}
        break;
        case 4:{if(b4.getText()=="")
                b4.setText("O");
        else 
        {computer();}}
        break;
        case 5:{if(b5.getText()=="")
                b5.setText("O");
        else 
        {computer();}}
        break;
        case 6:{if(b6.getText()=="")
                b6.setText("O");
        else 
        {computer();}}
        break;
        case 7:{if(b7.getText()=="")
                b7.setText("O");
        else 
        {computer();}}
        break;
        case 8:{if(b8.getText()=="")
                b8.setText("O");
        else 
        {computer();}}
        break;
        case 9:{if(b9.getText()=="")
                b9.setText("O");
        else 
        {computer();}}
        break;
    }
    }
    public void game()
    {
    l1.setText(String.valueOf(xcount));
    l2.setText(String .valueOf(ocount));
    }
    public void win()
    {
    String d1=b1.getText();
    String d2=b2.getText();
    String d3=b3.getText();
    String d4=b4.getText();
    String d5=b5.getText();
    String d6=b6.getText();
    String d7=b7.getText();
    String d8=b8.getText();
    String d9=b9.getText();
    if(d1==("X") && d2==("X") && d3==("X"))
    {
        xcount++; 
        game();
        b1.setBackground(Color.yellow);
        b2.setBackground(Color.yellow);
        b3.setBackground(Color.yellow);
    }
    if(d4==("X") && d5==("X") && d6==("X"))
    {
        xcount++; 
        game();
        b4.setBackground(Color.yellow);
        b5.setBackground(Color.yellow);
        b6.setBackground(Color.yellow);
    }
    if(d7==("X") && d8==("X") && d9==("X"))
    {
        xcount++; 
        game();
        b7.setBackground(Color.yellow);
        b8.setBackground(Color.yellow);
        b9.setBackground(Color.yellow);
    }
    if(d1==("X") && d5==("X") && d9==("X"))
    {
        xcount++; 
        game();
        b1.setBackground(Color.yellow);
        b5.setBackground(Color.yellow);
        b9.setBackground(Color.yellow);
    }
    if(d3==("X") && d5==("X") && d7==("X"))
    {
        xcount++; 
        game();
        b3.setBackground(Color.yellow);
        b5.setBackground(Color.yellow);
        b7.setBackground(Color.yellow);
    }
    if(d1==("X") && d4==("X") && d7==("X"))
    {
        xcount++; 
        game();
        b1.setBackground(Color.yellow);
        b4.setBackground(Color.yellow);
        b7.setBackground(Color.yellow);
    }
    if(d2==("X") && d5==("X") && d8==("X"))
    {
        xcount++; 
        game();
        b2.setBackground(Color.yellow);
        b5.setBackground(Color.yellow);
        b8.setBackground(Color.yellow);
    }
    if(d3==("X") && d6==("X") && d9==("X"))
    {
        xcount++; 
        game();
        b3.setBackground(Color.yellow);
        b6.setBackground(Color.yellow);
        b9.setBackground(Color.yellow);
    }
    if(d1==("O") && d2==("O") && d3==("O"))
    {
        ocount++; 
        game();
        b1.setBackground(Color.yellow);
        b2.setBackground(Color.yellow);
        b3.setBackground(Color.yellow);
    }
    if(d4==("O") && d5==("O") && d6==("O"))
    {
        ocount++; 
        game();
        b4.setBackground(Color.yellow);
        b5.setBackground(Color.yellow);
        b6.setBackground(Color.yellow);
    }
    if(d7==("O") && d8==("O") && d9==("O"))
    {
        ocount++; 
        game();
        b7.setBackground(Color.yellow);
        b8.setBackground(Color.yellow);
        b9.setBackground(Color.yellow);
    }
    if(d1==("O") && d5==("O") && d9==("O"))
    {
        ocount++; 
        game();
        b1.setBackground(Color.yellow);
        b5.setBackground(Color.yellow);
        b9.setBackground(Color.yellow);
    }
    if(d3==("O") && d5==("O") && d7==("O"))
    {
        ocount++; 
        game();
        b3.setBackground(Color.yellow);
        b5.setBackground(Color.yellow);
        b7.setBackground(Color.yellow);
    }
    if(d1==("O") && d4==("O") && d7==("O"))
    {
        ocount++; 
        game();
        b1.setBackground(Color.yellow);
        b4.setBackground(Color.yellow);
        b7.setBackground(Color.yellow);
    }
    if(d2==("O") && d5==("O") && d8==("O"))
    {
        ocount++; 
        game();
        b2.setBackground(Color.yellow);
        b5.setBackground(Color.yellow);
        b8.setBackground(Color.yellow);
    }
    if(d3==("O") && d6==("O") && d9==("O"))
    {
        ocount++; 
        game();
        b3.setBackground(Color.yellow);
        b6.setBackground(Color.yellow);
        b9.setBackground(Color.yellow);
    }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(singleplayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(singleplayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(singleplayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(singleplayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new singleplayer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Rest;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    // End of variables declaration//GEN-END:variables
}
